open "/System/Applications/Outlook.app"
sleep "3"
open "/Applications/Visual Studio Code.app"
sleep "5"
open "/Applications/Zotero.app"
sleep "5"
open "/Applications/Brave Browser.app"
sleep "10"
open "/Applications/Safari.app"
